// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsbbjyvkudpioszsixkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzYmJqeXZrdWRwaW9zenNpeGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTA4MTEsImV4cCI6MjA2NjIyNjgxMX0.sHRNS0gV4NDRiOYiiZ5hSb-ywN-Ai0dLVMg1YBgSOug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);